name: DashMachine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dashmachine
      run: docker build . --file Dockerfile --tag dashmachine:$(date +%s)
 
