name: ci

on:
  push:
    branches:
      - 'master'
env:
  # 设置 docker 镜像名
  IMAGE_NAME: dashmachine
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: actions/checkout@v2
        # 构建镜像，指定镜像名
      - name: Build image
        run: docker build . --file Dockerfile --tag dashmachine:$(date +%s)

      - name: Push image
        run: 
          docker tag dashmachine:$(date +%s)

          docker push dashmachine:$(date +%s)
